import bcrypt from 'bcryptjs';

export const data = {
    users: [
      {
        name: 'John',
        email: 'admin@example.com',
        password: bcrypt.hashSync('123456'),
        isAdmin: true,
      },
      {
        name: 'Jane',
        email: 'user@example.com',
        password: bcrypt.hashSync('123456'),
        isAdmin: false,
      },
    ],
    products: [
      {
        name: 'Stół drewniany',
        slug: 'stol-drewniany',
        category: 'Meble',
        image: '/images/stol1.jpg',
        price: 70,
        brand: 'Ikea',
        rating: 4.5,
        numReviews: 8,
        countInStock: 20,
        description: 'Piękny stół drewniany',
        isFeatured: true,
        //banner: '/images/banner1.jpg',
      },
      {
        name: 'Krzesło drewniane',
        slug: 'krzeslo-drewniane',
        category: 'Meble',
        image: '/images/krzeslo1.jpg',
        price: 120,
        brand: 'Castorama',
        rating: 4.0,
        numReviews: 18,
        countInStock: 40,
        description: 'Stylizowane krzesło drewniane',
        isFeatured: true,
        //banner: '/images/banner1.jpg',
      },
      {
        name: 'Krzesło plastikowe',
        slug: 'krzeslo-plasikowe',
        category: 'Meble',
        image: '/images/krzeslo2.jpg',
        price: 20,
        brand: 'Alinea',
        rating: 3.5,
        numReviews: 48,
        countInStock: 140,
        description: 'Praktyczne krzesło plastikowe',
        isFeatured: true,
        //banner: '/images/banner1.jpg',
      },
      {
        name: 'Lampa pokojowa',
        slug: 'lampa-pokojowa',
        category: 'Akcesoria',
        image: '/images/lampa1.jpg',
        price: 55,
        brand: 'Ikea',
        rating: 5.0,
        numReviews: 48,
        countInStock: 120,
        description: 'Praktyczna lampa pokojowa',
        isFeatured: true,
        //banner: '/images/banner1.jpg',
      },
      {
        name: 'Wieszak drewniany',
        slug: 'wieszak-drewniany',
        category: 'Akcesoria',
        image: '/images/wieszak1.jpg',
        price: 27,
        brand: 'Ikea',
        rating: 4.7,
        numReviews: 38,
        countInStock: 20,
        description: 'Drewniany wieszak na ubrania',
        isFeatured: true,
        //banner: '/images/banner1.jpg',
      },
      {
        name: 'Łóżko drewniane',
        slug: 'lozko-drewniane',
        category: 'Meble',
        image: '/images/lozko1.jpg',
        price: 320,
        brand: 'Castorama',
        rating: 5.0,
        numReviews: 38,
        countInStock: 10,
        description: 'Jednoosobowe łóżko drewniane',
        isFeatured: true,
        //banner: '/images/banner1.jpg',
      },
    ]
}